const githubResult = '''
{
  "total_count": 25,
  "incomplete_results": false,
  "items": [
    {
      "login": "giovanit",
      "id": 29869782,
      "node_id": "MDQ6VXNlcjI5ODY5Nzgy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/29869782?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanit",
      "html_url": "https://github.com/giovanit",
      "followers_url": "https://api.github.com/users/giovanit/followers",
      "following_url": "https://api.github.com/users/giovanit/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanit/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanit/orgs",
      "repos_url": "https://api.github.com/users/giovanit/repos",
      "events_url": "https://api.github.com/users/giovanit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanit/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GiovaniTricarico",
      "id": 41302197,
      "node_id": "MDQ6VXNlcjQxMzAyMTk3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/41302197?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GiovaniTricarico",
      "html_url": "https://github.com/GiovaniTricarico",
      "followers_url": "https://api.github.com/users/GiovaniTricarico/followers",
      "following_url": "https://api.github.com/users/GiovaniTricarico/following{/other_user}",
      "gists_url": "https://api.github.com/users/GiovaniTricarico/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GiovaniTricarico/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GiovaniTricarico/subscriptions",
      "organizations_url": "https://api.github.com/users/GiovaniTricarico/orgs",
      "repos_url": "https://api.github.com/users/GiovaniTricarico/repos",
      "events_url": "https://api.github.com/users/GiovaniTricarico/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GiovaniTricarico/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitrevisol",
      "id": 32503250,
      "node_id": "MDQ6VXNlcjMyNTAzMjUw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/32503250?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitrevisol",
      "html_url": "https://github.com/giovanitrevisol",
      "followers_url": "https://api.github.com/users/giovanitrevisol/followers",
      "following_url": "https://api.github.com/users/giovanitrevisol/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitrevisol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitrevisol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitrevisol/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitrevisol/orgs",
      "repos_url": "https://api.github.com/users/giovanitrevisol/repos",
      "events_url": "https://api.github.com/users/giovanitrevisol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitrevisol/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitrentin",
      "id": 13832145,
      "node_id": "MDQ6VXNlcjEzODMyMTQ1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13832145?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitrentin",
      "html_url": "https://github.com/giovanitrentin",
      "followers_url": "https://api.github.com/users/giovanitrentin/followers",
      "following_url": "https://api.github.com/users/giovanitrentin/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitrentin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitrentin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitrentin/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitrentin/orgs",
      "repos_url": "https://api.github.com/users/giovanitrentin/repos",
      "events_url": "https://api.github.com/users/giovanitrentin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitrentin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitestoni",
      "id": 19602535,
      "node_id": "MDQ6VXNlcjE5NjAyNTM1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/19602535?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitestoni",
      "html_url": "https://github.com/giovanitestoni",
      "followers_url": "https://api.github.com/users/giovanitestoni/followers",
      "following_url": "https://api.github.com/users/giovanitestoni/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitestoni/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitestoni/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitestoni/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitestoni/orgs",
      "repos_url": "https://api.github.com/users/giovanitestoni/repos",
      "events_url": "https://api.github.com/users/giovanitestoni/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitestoni/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitavares",
      "id": 54478414,
      "node_id": "MDQ6VXNlcjU0NDc4NDE0",
      "avatar_url": "https://avatars2.githubusercontent.com/u/54478414?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitavares",
      "html_url": "https://github.com/giovanitavares",
      "followers_url": "https://api.github.com/users/giovanitavares/followers",
      "following_url": "https://api.github.com/users/giovanitavares/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitavares/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitavares/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitavares/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitavares/orgs",
      "repos_url": "https://api.github.com/users/giovanitavares/repos",
      "events_url": "https://api.github.com/users/giovanitavares/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitavares/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanito",
      "id": 55927907,
      "node_id": "MDQ6VXNlcjU1OTI3OTA3",
      "avatar_url": "https://avatars0.githubusercontent.com/u/55927907?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanito",
      "html_url": "https://github.com/giovanito",
      "followers_url": "https://api.github.com/users/giovanito/followers",
      "following_url": "https://api.github.com/users/giovanito/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanito/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanito/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanito/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanito/orgs",
      "repos_url": "https://api.github.com/users/giovanito/repos",
      "events_url": "https://api.github.com/users/giovanito/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanito/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitoreli",
      "id": 1789661,
      "node_id": "MDQ6VXNlcjE3ODk2NjE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1789661?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitoreli",
      "html_url": "https://github.com/giovanitoreli",
      "followers_url": "https://api.github.com/users/giovanitoreli/followers",
      "following_url": "https://api.github.com/users/giovanitoreli/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitoreli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitoreli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitoreli/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitoreli/orgs",
      "repos_url": "https://api.github.com/users/giovanitoreli/repos",
      "events_url": "https://api.github.com/users/giovanitoreli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitoreli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GiovaniTech",
      "id": 75347438,
      "node_id": "MDQ6VXNlcjc1MzQ3NDM4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/75347438?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GiovaniTech",
      "html_url": "https://github.com/GiovaniTech",
      "followers_url": "https://api.github.com/users/GiovaniTech/followers",
      "following_url": "https://api.github.com/users/GiovaniTech/following{/other_user}",
      "gists_url": "https://api.github.com/users/GiovaniTech/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GiovaniTech/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GiovaniTech/subscriptions",
      "organizations_url": "https://api.github.com/users/GiovaniTech/orgs",
      "repos_url": "https://api.github.com/users/GiovaniTech/repos",
      "events_url": "https://api.github.com/users/GiovaniTech/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GiovaniTech/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitc",
      "id": 43519327,
      "node_id": "MDQ6VXNlcjQzNTE5MzI3",
      "avatar_url": "https://avatars0.githubusercontent.com/u/43519327?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitc",
      "html_url": "https://github.com/giovanitc",
      "followers_url": "https://api.github.com/users/giovanitc/followers",
      "following_url": "https://api.github.com/users/giovanitc/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitc/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitc/orgs",
      "repos_url": "https://api.github.com/users/giovanitc/repos",
      "events_url": "https://api.github.com/users/giovanitc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanithome",
      "id": 3584254,
      "node_id": "MDQ6VXNlcjM1ODQyNTQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3584254?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanithome",
      "html_url": "https://github.com/giovanithome",
      "followers_url": "https://api.github.com/users/giovanithome/followers",
      "following_url": "https://api.github.com/users/giovanithome/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanithome/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanithome/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanithome/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanithome/orgs",
      "repos_url": "https://api.github.com/users/giovanithome/repos",
      "events_url": "https://api.github.com/users/giovanithome/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanithome/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GiovaniTeran",
      "id": 58200482,
      "node_id": "MDQ6VXNlcjU4MjAwNDgy",
      "avatar_url": "https://avatars2.githubusercontent.com/u/58200482?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GiovaniTeran",
      "html_url": "https://github.com/GiovaniTeran",
      "followers_url": "https://api.github.com/users/GiovaniTeran/followers",
      "following_url": "https://api.github.com/users/GiovaniTeran/following{/other_user}",
      "gists_url": "https://api.github.com/users/GiovaniTeran/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GiovaniTeran/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GiovaniTeran/subscriptions",
      "organizations_url": "https://api.github.com/users/GiovaniTeran/orgs",
      "repos_url": "https://api.github.com/users/GiovaniTeran/repos",
      "events_url": "https://api.github.com/users/GiovaniTeran/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GiovaniTeran/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitier",
      "id": 29694554,
      "node_id": "MDQ6VXNlcjI5Njk0NTU0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/29694554?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitier",
      "html_url": "https://github.com/giovanitier",
      "followers_url": "https://api.github.com/users/giovanitier/followers",
      "following_url": "https://api.github.com/users/giovanitier/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitier/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitier/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitier/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitier/orgs",
      "repos_url": "https://api.github.com/users/giovanitier/repos",
      "events_url": "https://api.github.com/users/giovanitier/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitier/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitadei",
      "id": 13892401,
      "node_id": "MDQ6VXNlcjEzODkyNDAx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/13892401?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitadei",
      "html_url": "https://github.com/giovanitadei",
      "followers_url": "https://api.github.com/users/giovanitadei/followers",
      "following_url": "https://api.github.com/users/giovanitadei/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitadei/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitadei/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitadei/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitadei/orgs",
      "repos_url": "https://api.github.com/users/giovanitadei/repos",
      "events_url": "https://api.github.com/users/giovanitadei/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitadei/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitamanini",
      "id": 42223648,
      "node_id": "MDQ6VXNlcjQyMjIzNjQ4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/42223648?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitamanini",
      "html_url": "https://github.com/giovanitamanini",
      "followers_url": "https://api.github.com/users/giovanitamanini/followers",
      "following_url": "https://api.github.com/users/giovanitamanini/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitamanini/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitamanini/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitamanini/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitamanini/orgs",
      "repos_url": "https://api.github.com/users/giovanitamanini/repos",
      "events_url": "https://api.github.com/users/giovanitamanini/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitamanini/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GiovaniTI",
      "id": 38923571,
      "node_id": "MDQ6VXNlcjM4OTIzNTcx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/38923571?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GiovaniTI",
      "html_url": "https://github.com/GiovaniTI",
      "followers_url": "https://api.github.com/users/GiovaniTI/followers",
      "following_url": "https://api.github.com/users/GiovaniTI/following{/other_user}",
      "gists_url": "https://api.github.com/users/GiovaniTI/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GiovaniTI/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GiovaniTI/subscriptions",
      "organizations_url": "https://api.github.com/users/GiovaniTI/orgs",
      "repos_url": "https://api.github.com/users/GiovaniTI/repos",
      "events_url": "https://api.github.com/users/GiovaniTI/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GiovaniTI/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitt",
      "id": 75735361,
      "node_id": "MDQ6VXNlcjc1NzM1MzYx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/75735361?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitt",
      "html_url": "https://github.com/giovanitt",
      "followers_url": "https://api.github.com/users/giovanitt/followers",
      "following_url": "https://api.github.com/users/giovanitt/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitt/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitt/orgs",
      "repos_url": "https://api.github.com/users/giovanitt/repos",
      "events_url": "https://api.github.com/users/giovanitt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitjs",
      "id": 56462231,
      "node_id": "MDQ6VXNlcjU2NDYyMjMx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/56462231?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitjs",
      "html_url": "https://github.com/giovanitjs",
      "followers_url": "https://api.github.com/users/giovanitjs/followers",
      "following_url": "https://api.github.com/users/giovanitjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitjs/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitjs/orgs",
      "repos_url": "https://api.github.com/users/giovanitjs/repos",
      "events_url": "https://api.github.com/users/giovanitjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitjs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitechnolog",
      "id": 32130306,
      "node_id": "MDQ6VXNlcjMyMTMwMzA2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/32130306?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitechnolog",
      "html_url": "https://github.com/giovanitechnolog",
      "followers_url": "https://api.github.com/users/giovanitechnolog/followers",
      "following_url": "https://api.github.com/users/giovanitechnolog/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitechnolog/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitechnolog/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitechnolog/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitechnolog/orgs",
      "repos_url": "https://api.github.com/users/giovanitechnolog/repos",
      "events_url": "https://api.github.com/users/giovanitechnolog/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitechnolog/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitania",
      "id": 70595338,
      "node_id": "MDQ6VXNlcjcwNTk1MzM4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/70595338?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitania",
      "html_url": "https://github.com/giovanitania",
      "followers_url": "https://api.github.com/users/giovanitania/followers",
      "following_url": "https://api.github.com/users/giovanitania/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitania/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitania/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitania/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitania/orgs",
      "repos_url": "https://api.github.com/users/giovanitania/repos",
      "events_url": "https://api.github.com/users/giovanitania/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitania/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitierweb",
      "id": 29694559,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI5Njk0NTU5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/29694559?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitierweb",
      "html_url": "https://github.com/giovanitierweb",
      "followers_url": "https://api.github.com/users/giovanitierweb/followers",
      "following_url": "https://api.github.com/users/giovanitierweb/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitierweb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitierweb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitierweb/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitierweb/orgs",
      "repos_url": "https://api.github.com/users/giovanitierweb/repos",
      "events_url": "https://api.github.com/users/giovanitierweb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitierweb/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanith",
      "id": 54237835,
      "node_id": "MDQ6VXNlcjU0MjM3ODM1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/54237835?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanith",
      "html_url": "https://github.com/giovanith",
      "followers_url": "https://api.github.com/users/giovanith/followers",
      "following_url": "https://api.github.com/users/giovanith/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanith/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanith/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanith/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanith/orgs",
      "repos_url": "https://api.github.com/users/giovanith/repos",
      "events_url": "https://api.github.com/users/giovanith/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanith/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovaniteodoro82",
      "id": 72769908,
      "node_id": "MDQ6VXNlcjcyNzY5OTA4",
      "avatar_url": "https://avatars0.githubusercontent.com/u/72769908?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovaniteodoro82",
      "html_url": "https://github.com/giovaniteodoro82",
      "followers_url": "https://api.github.com/users/giovaniteodoro82/followers",
      "following_url": "https://api.github.com/users/giovaniteodoro82/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovaniteodoro82/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovaniteodoro82/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovaniteodoro82/subscriptions",
      "organizations_url": "https://api.github.com/users/giovaniteodoro82/orgs",
      "repos_url": "https://api.github.com/users/giovaniteodoro82/repos",
      "events_url": "https://api.github.com/users/giovaniteodoro82/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovaniteodoro82/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovanitang",
      "id": 20180850,
      "node_id": "MDQ6VXNlcjIwMTgwODUw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/20180850?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovanitang",
      "html_url": "https://github.com/giovanitang",
      "followers_url": "https://api.github.com/users/giovanitang/followers",
      "following_url": "https://api.github.com/users/giovanitang/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovanitang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovanitang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovanitang/subscriptions",
      "organizations_url": "https://api.github.com/users/giovanitang/orgs",
      "repos_url": "https://api.github.com/users/giovanitang/repos",
      "events_url": "https://api.github.com/users/giovanitang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovanitang/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "giovaniteixeira",
      "id": 48409898,
      "node_id": "MDQ6VXNlcjQ4NDA5ODk4",
      "avatar_url": "https://avatars1.githubusercontent.com/u/48409898?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giovaniteixeira",
      "html_url": "https://github.com/giovaniteixeira",
      "followers_url": "https://api.github.com/users/giovaniteixeira/followers",
      "following_url": "https://api.github.com/users/giovaniteixeira/following{/other_user}",
      "gists_url": "https://api.github.com/users/giovaniteixeira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giovaniteixeira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giovaniteixeira/subscriptions",
      "organizations_url": "https://api.github.com/users/giovaniteixeira/orgs",
      "repos_url": "https://api.github.com/users/giovaniteixeira/repos",
      "events_url": "https://api.github.com/users/giovaniteixeira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giovaniteixeira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
 ''';
